<?php

/**
 * @file
 * API documentation for taxonomy_xml_fields module.
 */

/**
 * HOOKS
 */

/**
 * Respond to the namespaces being declared for a taxonomy import.
 *
 * This hook allows the array of namespaces generated by rdf_get_namespaces()
 * to be altered before processing taxonomy_term predicates found in the vocabulary .source
 *
 * @param &$namespaces
 *   The array of namespaces to look for in the format:
 *   $namespaces[<abbreviation>] = <uri>
 *   
 *   i.e. $namespaces['skos'] = 'http://www.w3.org/2004/02/skos/core#';
 * 
 * @see taxonomy_xml_fields_get_namespaces($vid)
 * @see taxonomy_xml_fields_taxonomy_xml_fields_namespaces($namespaces)
 * 
 */
function hook_taxonomy_xml_fields_namespaces($namepsaces) {
  return $namespaces;
}